// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn3HKEY09_raI4P5ls3Xtgq-UlyYxyTH8',
    appId: '1:706863162875:web:e34c2d28085b2f85b7575e',
    messagingSenderId: '706863162875',
    projectId: 'quizzity-c05ee',
    authDomain: 'quizzity-c05ee.firebaseapp.com',
    storageBucket: 'quizzity-c05ee.appspot.com',
    measurementId: 'G-T4HEHH7ZS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWXZo1acNPxOj64_r4tX07soBR1HUvB9g',
    appId: '1:706863162875:android:84a4738164551fc1b7575e',
    messagingSenderId: '706863162875',
    projectId: 'quizzity-c05ee',
    storageBucket: 'quizzity-c05ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8sC5vHmRX8u3eHXd6aF9XyZ48k32XfFg',
    appId: '1:706863162875:ios:150bdbaf1cf1e894b7575e',
    messagingSenderId: '706863162875',
    projectId: 'quizzity-c05ee',
    storageBucket: 'quizzity-c05ee.appspot.com',
    iosBundleId: 'com.app.quizzity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8sC5vHmRX8u3eHXd6aF9XyZ48k32XfFg',
    appId: '1:706863162875:ios:b04f424ae88da258b7575e',
    messagingSenderId: '706863162875',
    projectId: 'quizzity-c05ee',
    storageBucket: 'quizzity-c05ee.appspot.com',
    iosBundleId: 'com.app.quizzity.RunnerTests',
  );
}
